import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
dotenv.config({ path: 'C:/Users/i_lov/OneDrive/デスクトップ/gummy-wiki/.env.local' })
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)

const items = [
  // 前回セッション summary（フォルダ13・14・10前半）
  {maker:'バンダイ', name:'にゃーんとのびたグミ', flavor:null},
  {maker:'カンロ', name:'しずくの宝石グミ', flavor:'芳潤白桃味'},
  {maker:'アトリオン製菓', name:'コーラパンチXハードグミ', flavor:null},
  {maker:'カンロ', name:'黒猫グミ', flavor:'ミグたん'},
  {maker:'全国農協食品', name:'ダブルゴールドグミ', flavor:null},
  {maker:'ブルボン', name:'フェットチーネグミPREMIUM', flavor:'ぶどう三姉妹味'},
  {maker:'セブン＆アイ・ホールディングス', name:'セブンプレミアム グミまる', flavor:'白桃味'},
  {maker:'セブン＆アイ・ホールディングス', name:'セブンプレミアム グミまる', flavor:'巨峰味'},
  {maker:'UHA味覚糖', name:'むっちりグミ', flavor:'メロンソーダ'},
  {maker:'UHA味覚糖', name:'むっちりグミ', flavor:'さわやかメロンソーダ'},
  {maker:'春日井製菓', name:'グミだよ。', flavor:'ビーチフラッペ味'},
  {maker:'春日井製菓', name:'グミだよ。', flavor:'クリームソーダ味'},
  {maker:'やおきん', name:'コーラグミ', flavor:null},
  {maker:'やおきん', name:'ぶどうグミ', flavor:null},
  {maker:'やおきん', name:'みかんグミ', flavor:null},
  {maker:'ライオン菓子', name:'レモングミ', flavor:null},

  // フォルダ10（165-173）
  {maker:'春日井製菓', name:'リプトンフルーツインティーグミ アソートパック', flavor:null},
  {maker:'カンロ', name:'カンデミーナグミ', flavor:'カタメコイメ アツサマシマシ'},
  {maker:'フロンティア物産', name:'NERds グミクラスター', flavor:null},
  {maker:'全国農協食品', name:'ニッポンエール 山形県産さくらんぼグミ', flavor:null},
  {maker:'ピエログルマン', name:'パイナップルグミ', flavor:null},
  {maker:'クリート', name:'おたべ監修 生八つ橋グミ', flavor:null},
  {maker:'マツモトキヨシ', name:'EXSTRONG RUN&GUN エナジーグミ', flavor:null},
  {maker:'UHA味覚糖', name:'コーラ組&ソーダ組', flavor:null},
  {maker:'UHA味覚糖', name:'リンクグミ', flavor:null},
  {maker:'fini', name:'Magic carpets', flavor:null},
  {maker:'ライオン菓子', name:'蜜入りりんごグミ', flavor:null},
  {maker:'ロッテ', name:"Fit's BIGグミ", flavor:'グレープ&マスカット'},
  {maker:'旺旺・ジャパン', name:'アジアンスイーツシリーズ 杏仁豆腐味グミ', flavor:null},
  {maker:'眉雀飴本舗', name:'しろくまの幸せにくきゅうグミ', flavor:'メロンクリームソーダ味'},
  {maker:'カンロ', name:'カンデミーナグミ', flavor:'二刀間'},
  {maker:'UHA味覚糖', name:'つむグミ TETRIS', flavor:null},
  {maker:'豊産業', name:'トローリ プラネットグミ', flavor:null},
  {maker:'ブルボン', name:'プルプグミ', flavor:'ぶどう味'},
  {maker:'春日井製菓', name:'つぶグミプレミアム', flavor:'濃厚オレンジ'},
  {maker:'カンロ', name:'4Dグミ', flavor:'ミニフルーツパイナップル'},
  {maker:'バンダイ', name:'ドラえもんグミ', flavor:'グレープ味'},
  {maker:'春日井製菓', name:'つぶグミのもと', flavor:null},
  {maker:'カンロ', name:'あそぼん！グミ', flavor:'ワクワクパック'},
  {maker:'フルタ製菓', name:'プリキュアグミ', flavor:null},
  {maker:'フルタ製菓', name:'ドラえもんグミ', flavor:null},
  {maker:'フルタ製菓', name:'ゼンカイジャーグミ', flavor:null},
  {maker:'カンロ', name:'カンデミーナグミ', flavor:'激アツヘビー級パック'},
  {maker:'明治チューインガム', name:'グミのわ', flavor:null},
  {maker:'カバヤ食品', name:'ミナギリン グミ', flavor:null},
  {maker:'カバヤ食品', name:'ピュアラルグミ', flavor:'完熟白桃'},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'イタリアンレモン味'},
  {maker:'チュッパチャプス', name:'Pandabears', flavor:null},
  {maker:'UHA味覚糖', name:'むっちりグミ', flavor:'がぶ飲み2種アソート'},
  {maker:'カンロ', name:'グミッツェルプチ パーティBOX', flavor:null},
  {maker:'春日井製菓', name:'つぶグミ', flavor:'バカンス'},
  {maker:'カンロ', name:'ピュレグミ', flavor:'白桃味'},
  {maker:'春日井製菓', name:'たっぷりグミのしろ', flavor:'ブドウ&リンゴ味'},
  {maker:'クラシエフーズ', name:'グミつれた', flavor:'グレープ味'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'国産熱メロン'},
  {maker:'UHA味覚糖', name:'コグミ 乙女のジュエリーグミ', flavor:null},
  {maker:'明治', name:'果汁グミ', flavor:'和歌山県産南高梅'},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'あまおう苺味'},
  {maker:'ロッテ', name:"Fit'sグミ", flavor:'ゴツンとふにゃん みかん&いちご'},
  {maker:'カンロ', name:'カンデミーナグミ', flavor:'ご決断を！'},

  // フォルダ11（174-192）
  {maker:'UHA味覚糖', name:'あおもりグミ', flavor:null},
  {maker:'カンロ', name:'ヒトツブカンロ 幸せのポストingグミッツェル', flavor:null},
  {maker:'カンロ', name:'ヒトツブカンロ 幸せのグミッツェルプチ', flavor:null},
  {maker:'カンロ', name:'オン・モードグミ', flavor:null},
  {maker:'ノーベル製菓', name:'ペタグーグミ', flavor:'メロンソーダ味'},
  {maker:'カンロ', name:'ポストingグミッツェル クローバー', flavor:null},
  {maker:'モントワール', name:'バズーカキャンディブランズ ジューシードロップグミ', flavor:'ソーダ味'},
  {maker:'モントワール', name:'バズーカキャンディブランズ ジューシードロップグミ', flavor:'グレープ味'},
  {maker:'カンロ', name:'ピュレグミ', flavor:'柑橘ヨーグルト味'},
  {maker:'ブルボン', name:'PRIMEフェットチーネグミ', flavor:'レモン味'},
  {maker:'ブルボン', name:'PRIMEフェットチーネグミ', flavor:'贅沢グレープ味'},
  {maker:'カンロ', name:'ピュレグミ', flavor:'柑橘みヨーグルト'},
  {maker:'カンロ', name:'○△□グミ', flavor:'グレープ'},
  {maker:'ハート', name:'4Dグミ', flavor:'ディズニーキャラクター'},
  {maker:'早川製菓', name:'すみっコぐらし 杏仁パイングミ', flavor:null},
  {maker:'ノーベル製菓', name:'ペタグーグミ', flavor:'グレープ味'},
  {maker:'カンロ', name:'カンデミーナグミ', flavor:'ぶどう盛ライブ'},
  {maker:'明治', name:'大人果汁グミ', flavor:'レモンビール'},
  {maker:'カバヤ食品', name:'タフグミ', flavor:'超刺激エナジー'},
  {maker:'ピエログルマン', name:'オーガニックフルーツミックスグミ', flavor:null},
  {maker:'カンロ', name:'4Dグミブロックス', flavor:null},
  {maker:'カンロ', name:'4Dグミポップベア', flavor:null},
  {maker:'全国農協食品', name:'ニッポンエール 山形県産 ぶどうグミ', flavor:null},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'ホワイトソーダ味'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'蜜入りりんご'},
  {maker:'不二家', name:'ドールグミ', flavor:'パイナップル'},
  {maker:'モントワール', name:'メロングミ', flavor:null},
  {maker:'UHA味覚糖', name:'ツイステグミ', flavor:'ツイステッドフルーツ味'},
  {maker:'カンロ', name:'グミッツェルプチの雪遊び', flavor:null},
  {maker:'モントワール', name:'桜島小みかんグミ', flavor:null},
  {maker:'カンロ', name:'ピュレグミ', flavor:'レモン ポケモン'},
  {maker:'ノースカラーズ', name:'4Dグミ', flavor:'サイダー&コーラ'},
  {maker:'眉雀飴本舗', name:'幸せにくきゅうグミ', flavor:'ミックスベリー味'},
  {maker:'眉雀飴本舗', name:'幸せにくきゅうグミ', flavor:'グレープ味'},
  {maker:'バンダイ', name:'ヒーリングっどプリキュア グミ', flavor:'りんご'},
  {maker:'UHA味覚糖', name:'とろけるグミ', flavor:'湘南ゴールドグミ'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'みかん&ピンクグレープフルーツ'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'白桃&桜桃'},
  {maker:'カンロ', name:'100%グミ', flavor:'温州みかん'},
  {maker:'カンロ', name:'濃いピュレグミ', flavor:'いちご味'},
  {maker:'春日井製菓', name:'つぶグミプレミアム', flavor:'濃厚ぶどう'},
  {maker:'春日井製菓', name:'つぶグミプレミアム', flavor:'濃厚桃'},
  {maker:'ブルボン', name:'プルプグミ', flavor:'みかん味'},
  {maker:'カンロ', name:'ピュレグミ', flavor:'濃いいちご'},
  {maker:'ノーベル製菓', name:'サワーズグミ', flavor:'乳酸菌ドリンク味'},
  {maker:'ロッテ', name:"Fit'sグミ", flavor:'ゴツンとふにゃん グレープ&ビーチ'},
  {maker:'ノーベル製菓', name:'ちびサワーズグミ', flavor:'エナジードリンクアソート'},
  {maker:'春日井製菓', name:'リプトンフルーツインティーグミ', flavor:'サワーフルーツ'},
  {maker:'カルビー', name:'ランチグミ', flavor:null},
  {maker:'カンロ', name:'ザ・ストロンググミ', flavor:'濃厚コーラ味'},
  {maker:'UHA味覚糖', name:'つむモスグミ 2', flavor:null},
  {maker:'クリート', name:'sonna banana グミ', flavor:null},
  {maker:'カンロ', name:'ピュレグミ', flavor:'でんげきトロピカ味2'},
  {maker:'春日井製菓', name:'つぶグミ', flavor:'ライフガード'},
  {maker:'ノーベル製菓', name:'サワーズ アソートグミ', flavor:null},
  {maker:'春日井製菓', name:'つぶグミ', flavor:'濃密ベリー'},
  {maker:'旺旺・ジャパン', name:'コーラグミ 5連パック', flavor:null},
  {maker:'fini', name:'HOLYDAY フライドエッググミ', flavor:null},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'金のキウイ'},
  {maker:'ライオン菓子', name:'ナタデココ杏仁ピーチグミ', flavor:null},
  {maker:'不二家', name:'ドールグミ贅沢ダブル', flavor:'マスカット&グレープ'},
  {maker:'カンロ', name:'カンデミーナグミ', flavor:'シークワーサー'},
  {maker:'ろすまりん', name:'青森限定りんごのグミ', flavor:null},
  {maker:'フルタ製菓', name:'魔進戦隊キラメイジャーグミ', flavor:null},
  {maker:'カンロ', name:'100%グミ', flavor:'マスカット'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'白桃&すもも'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'みかん&はっさく'},
  {maker:'クリート', name:'コメダ珈琲グミ', flavor:'メロンソーダ&レモンスカッシュ'},
  {maker:'カンロ', name:'カンデミーナグミ', flavor:'個包装アソート'},
  {maker:'ブルボン', name:'グミモッツァ', flavor:'ヨーグルト味'},
  {maker:'バンダイ', name:'魚ぎょっと釣りグミ', flavor:'ソーダ&オレンジ味'},
  {maker:'トローリ', name:'ミニバーガーグミ', flavor:null},
  {maker:'カンロ', name:'ピュレグミ', flavor:'個包装アソート'},
  {maker:'UHA味覚糖', name:'とろけるグミ', flavor:'有田みかん'},
  {maker:'明治', name:'果汁グミ', flavor:'ゴールドキウイ'},
  {maker:'UHA味覚糖', name:'むっちりグミ', flavor:'ライフガード'},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'グレープソーダ味'},
  {maker:'ノーベル製菓', name:'ペタグーグミ', flavor:'レモン味'},
  {maker:'クラシエフーズ', name:'復活恐竜グミ', flavor:null},
  {maker:'UHA味覚糖', name:'リセットうめグミ', flavor:null},
  {maker:'バンダイ', name:'くまのプーさん ぷにぷにおしりのプーさんグミ', flavor:null},
  {maker:'UHA味覚糖', name:'にゃんコグミ', flavor:null},
  {maker:'カンロ', name:'カンデミーナグミミラクルV', flavor:null},
  {maker:'カンロ', name:'ぐむにーグミ', flavor:null},
  {maker:'クリート', name:'まぐろ三昧グミ', flavor:null},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'黄金パイン'},
  {maker:'春日井製菓', name:'つぶグミ', flavor:'青春ソーダ'},
  {maker:'カバヤ食品', name:'タフグミ', flavor:'岩塩レモン'},
  {maker:'カンロ', name:'ピュレグミ', flavor:'でんげきトロピカ味'},
  {maker:'カバヤ食品', name:'ピュアラルグミ', flavor:'マンゴー'},
  {maker:'江崎グリコ', name:'アイスの実グミ', flavor:'ぶどう'},
  {maker:'江崎グリコ', name:'アイスの実グミ', flavor:'梨'},
  {maker:'UHA味覚糖', name:'さけるグミ', flavor:'コーラ'},
  {maker:'明治', name:'果汁グミ', flavor:'ラ・フランス'},
  {maker:'春日井製菓', name:'つぶグミ', flavor:'濃密ベリー'},

  // フォルダ12（67-79）
  {maker:'クラシエフーズ', name:'にじいろひもグミ', flavor:'ぶどうソーダ味'},
  {maker:'ドルチェ', name:'フルーチェグミ', flavor:'イチゴ'},
  {maker:'アイデアパッケージ', name:'天使のグミ', flavor:'褒美の濃厚甘熟マンゴー味'},
  {maker:'ハート', name:'バベットスンスングミ', flavor:null},
  {maker:'ハート', name:'マイメロディ・クロミの4Dグミ', flavor:'アップル&グレープ味'},
  {maker:'メリーゴーランド', name:'タコグミ', flavor:'オレンジ風味'},
  {maker:'メリーゴーランド', name:'タコグミ', flavor:'コーラ風味'},
  {maker:'アトリオン製菓', name:'ヨーグレットグミfruit', flavor:'ブルーベリーヨーグルト味'},
  {maker:'クリート', name:'むっち実グミ', flavor:'オレンジ味'},
  {maker:'カンロ', name:'カンデミーナグミWインパクト', flavor:'シャイニングマスカットソーダ'},
  {maker:'カンロ', name:'4Dグミ', flavor:'旅路のマジックアワー'},
  {maker:'セブン＆アイ・ホールディングス', name:'セブンプレミアム チョコっとグミ', flavor:'清見オレンジ味'},
  {maker:'セブン＆アイ・ホールディングス', name:'セブンプレミアム チョコっとグミ', flavor:'沖縄県いりおもて島産パイナップル味'},
  {maker:'カンロ', name:'しずくの宝石グミ', flavor:'贅沢シャインマスカット味'},
  {maker:'カンロ', name:'4Dグミ', flavor:'ムーミン'},
  {maker:'セブン＆アイ・ホールディングス', name:'セブンプレミアム グミカク', flavor:'コーラ風味'},
  {maker:'セブン＆アイ・ホールディングス', name:'セブンプレミアム グミカク', flavor:'サイダー風味'},
  {maker:'ノーベル製菓', name:'ペタグーグミ', flavor:'シャインマスカット味'},
  {maker:'不二家', name:'ジャムグミ', flavor:'いちご'},
  {maker:'ギンビス', name:'たべっ子どうぶつ グミ', flavor:'パイナップル'},
  {maker:'マイウェイ', name:'スウェーデンスタイルグミ', flavor:null},
  {maker:'バンダイ', name:'なまけぐみ', flavor:null},
  {maker:'カンロ', name:'ピュレグミ', flavor:'なつももソーダ'},
  {maker:'タクマ食品', name:'完熟メロングミ', flavor:null},
  {maker:'タクマ食品', name:'完熟マンゴーグミ', flavor:null},
  {maker:'カンロ', name:'カンデミーナグミWインパクト', flavor:'衝撃ラララ・ライチソーダ'},
  {maker:'ノースカラーズ', name:'富士山サイダーグミ', flavor:null},
  {maker:'クリート', name:'レインボーキューブグミ', flavor:null},
  {maker:'UHA味覚糖', name:'コグミPREMIUM', flavor:'ドール'},
  {maker:'ブルボン', name:'フェットチーネグミPREMIUM', flavor:'ピーチパイン'},
  {maker:'タクマ食品', name:'もっちり塩トマトグミ', flavor:null},
  {maker:'モントワール', name:'クイック塩グミ', flavor:'パイン味'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'北海道ダブルメロン'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'沖縄産パイナップルスパークリング'},
  {maker:'クラシエフーズ', name:'チュッパチャプス すっぱいサワーベルトグミ', flavor:'ミックスフルーツ味'},
  {maker:'ワカサ観光物産', name:'メロンクマグミ', flavor:null},
  {maker:'マルストレーディング', name:'動物グミ', flavor:'陸の動物'},
  {maker:'マルストレーディング', name:'動物グミ', flavor:'海の動物'},
  {maker:'バンダイ', name:'どうぶつのおしりグミ', flavor:'ピーチ味'},
  {maker:'メリーゴーランド', name:'剥く生グミ', flavor:null},
  {maker:'クリート', name:'むっち実グミ', flavor:'青りんご味'},
  {maker:'ノースカラーズ', name:'町村農場の生乳から作った練乳のグミ', flavor:null},
  {maker:'カンロ', name:'カンデミーナグミ', flavor:'噛みごたえール'},
  {maker:'ギンビス', name:'たべっ子どうぶつグミ', flavor:'ぶどう味'},
  {maker:'明治', name:'果汁グミ', flavor:'ダークチェリーMIX'},
  {maker:'眉雀飴本舗', name:'幸せにくきゅうグミ', flavor:'レモン味'},
  {maker:'アトリオン製菓', name:'クリームソーダのフリしたいグミ', flavor:null},
  {maker:'メリーゴーランド', name:'皮が剥けるグミ', flavor:'3種アソート'},
  {maker:'早川製菓', name:'らぷいーず すもっぴとぴょんちーのももグミ', flavor:null},
  {maker:'ブルボン', name:'しゃりもにグミ', flavor:'ひんやりマンゴー味'},
  {maker:'ハッピーポケット', name:'ブドウグミ', flavor:null},
  {maker:'ハッピーポケット', name:'キウイグミ', flavor:null},
  {maker:'クリート', name:'抹茶チョコがけピーチグミ', flavor:null},
  {maker:'ハート', name:'ハンギョドンの4Dグミ', flavor:null},
  {maker:'クリート', name:'レミたんグミ', flavor:null},
  {maker:'ハート', name:'フローズン2 オラフの4Dグミ', flavor:null},
  {maker:'クリート', name:'植物生まれのシャインマスカットグミ', flavor:null},
  {maker:'ノーベル製菓', name:'シンサワーズグミ', flavor:'グレープ味'},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'つぶつぶフルーツティー味'},
  {maker:'クリート', name:'むきむきひよこグミ', flavor:null},
  {maker:'クラシエフーズ', name:'チュッパチャプス サワーベルトグミ', flavor:null},
  {maker:'アイデアパッケージ', name:'天使のグミ', flavor:'恵みの濃厚蜜りんご味'},
  {maker:'バンダイ', name:'ドラえもん ころがしじゃんけんグミ', flavor:null},
  {maker:'クリート', name:'グミのグミ', flavor:'グッドなグレープ味'},
  {maker:'クリート', name:'グミのグミ', flavor:'ミラクルなオレンジ味'},
  {maker:'カンロ', name:'ピュレグミプレミアム', flavor:'シチリア産レモンのピンクレモネード'},
  {maker:'眉雀飴本舗', name:'OSAMU GOODSグミ', flavor:null},
  {maker:'マルストレーディング', name:'くだものみたいな皮がむけるぐみ', flavor:'ライチ'},
  {maker:'マルストレーディング', name:'くだものみたいな皮がむけるぐみ', flavor:'ピーチ'},
  {maker:'マルストレーディング', name:'くだものみたいな皮がむけるグミ', flavor:'アップルマンゴー'},
  {maker:'マルストレーディング', name:'くだものみたいな皮がむけるグミ', flavor:'シャインマスカット'},
  {maker:'クリート', name:'ととのいドリンクグミ', flavor:null},

  // フォルダ12（326-330）
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'メロンソーダ味'},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'すっぱい梅味'},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'コーラ味 ハードボイルド'},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'イタリアンピーチ味'},
  {maker:'ブルボン', name:'フェットチーネグミ', flavor:'イタリアングレープ味'},
  {maker:'カバヤ食品', name:'ピュアラルグミ', flavor:'りんご'},
  {maker:'春日井製菓', name:'つぶグミ', flavor:'サンダー'},
  {maker:'春日井製菓', name:'つぶグミ', flavor:null},
  {maker:'カバヤ食品', name:'ちいグミ', flavor:null},
  {maker:'ロッテ', name:'だいすき！ピカチュウグミ', flavor:null},
  {maker:'カバヤ食品', name:'タフグミ', flavor:'乳酸菌ドリンク味'},
  {maker:'不二家', name:'アンパンマングミ', flavor:null},
  {maker:'カバヤ食品', name:'ピュアラルグミ', flavor:'いちご'},
  {maker:'カバヤ食品', name:'ピュアラルグミ', flavor:'沖縄パイン'},
]

const { data: existing } = await sb.from('gummies').select('name,flavor,maker')
const registeredSet = new Set((existing ?? []).map(g => `${g.maker}__${g.name}__${g.flavor??''}`))

let registered = 0, skipped = 0
for (const t of items) {
  const key = `${t.maker}__${t.name}__${t.flavor??''}`
  if (registeredSet.has(key)) { skipped++; continue }
  const {error} = await sb.from('gummies').insert({...t, image_url:null, description:null, rakuten_url:null})
  if (error) console.log(`❌ ${t.name} ${error.message}`)
  else { registered++; registeredSet.add(key) }
}
console.log(`完了: ${registered}件登録 / ${skipped}件スキップ`)
